// API client for "Autenticación con JWT Middleware en Express.js y Functional Interceptor en Angular 17" (generated by gherkin-ai).
// Contract: POST /api/v1/autenticacion-con-jwt-middleware-en-express-js-y-functional-interceptor-en-angular17/{id}/{command} -> 201 { type, aggregateId, version }

export const COMMANDS = ['process_autenticacion_con_jwt_middleware_en_express_js_y_functional_interceptor_en_angular17'] as const;
export type CommandName = (typeof COMMANDS)[number];

export interface CommandResult {
  type: string;
  aggregateId: string;
  version: number;
}

export class ApiError extends Error {
  constructor(public readonly status: number, message: string) {
    super(message);
    this.name = 'ApiError';
  }
}

export interface ClientOptions {
  /** Backend origin, e.g. https://api.example.com (default: same origin). */
  baseUrl?: string;
  tenantId?: string;
  fetch?: typeof fetch;
}

export interface ExecuteOptions {
  /** Sent as X-Idempotency-Key so retries are safe. */
  idempotencyKey?: string;
}

export function createAutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17Client(options: ClientOptions = {}) {
  const baseUrl = (options.baseUrl ?? '').replace(/\/$/, '');
  const doFetch = options.fetch ?? ((...args: Parameters<typeof fetch>) => fetch(...args));

  async function execute(id: string, command: CommandName, payload: Record<string, unknown> = {}, opts: ExecuteOptions = {}): Promise<CommandResult> {
    const headers: Record<string, string> = { 'Content-Type': 'application/json', Accept: 'application/json' };
    if (options.tenantId) headers['X-Tenant-Id'] = options.tenantId;
    if (opts.idempotencyKey) headers['X-Idempotency-Key'] = opts.idempotencyKey;

    const res = await doFetch(`${baseUrl}/api/v1/autenticacion-con-jwt-middleware-en-express-js-y-functional-interceptor-en-angular17/${encodeURIComponent(id)}/${command}`, {
      method: 'POST',
      headers,
      body: JSON.stringify(payload)
    });
    const body = await res.json().catch(() => ({}));
    if (!res.ok) throw new ApiError(res.status, (body as { detail?: string }).detail ?? `Request failed with status ${res.status}`);
    return body as CommandResult;
  }

  return {
    execute,
    processAutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17: (id: string, payload?: Record<string, unknown>, opts?: ExecuteOptions) => execute(id, 'process_autenticacion_con_jwt_middleware_en_express_js_y_functional_interceptor_en_angular17', payload, opts),
  };
}

export type AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17Client = ReturnType<typeof createAutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17Client>;
