// Domain kernel for "Autenticación con JWT Middleware en Express.js y Functional Interceptor en Angular 17" (generated by gherkin-ai).
// Pure domain logic: no framework, no I/O. Extend the command handlers with your business rules.

export type AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17State = 'PENDING';
export type AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17EventType = 'ProcessAutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17Completed' | 'AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17Processed';

export interface AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17DomainEvent {
  type: AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17EventType;
  aggregateId: string;
  version: number;
  occurredOn: Date;
  payload: Record<string, unknown>;
}

export interface AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17Command {
  /** Identifier of the aggregate the command targets. */
  id: string;
  payload?: Record<string, unknown>;
}

export class DomainValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'DomainValidationError';
  }
}

export class AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17Aggregate {
  private _state: AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17State = 'PENDING';
  private _version = 0;
  private readonly _events: AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17DomainEvent[] = [];

  constructor(public readonly id: string) {
    if (!id || !id.trim()) throw new DomainValidationError('AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17 id is required');
  }

  get state(): AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17State {
    return this._state;
  }

  get version(): number {
    return this._version;
  }

  /** Events recorded since the aggregate was loaded (to be saved via an outbox). */
  get pendingEvents(): readonly AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17DomainEvent[] {
    return this._events;
  }

  processAutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17(command: AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17Command): AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17DomainEvent {
    this.assertValid(command);
    return this.record('ProcessAutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17Completed', command.payload ?? {});
  }

  private assertValid(command: AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17Command): void {
    if (!command || !command.id || !command.id.trim()) throw new DomainValidationError('Command id is required');
    if (command.id !== this.id) throw new DomainValidationError(`Command targets ${command.id}, not ${this.id}`);
  }

  private record(type: AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17EventType, payload: Record<string, unknown>): AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17DomainEvent {
    this._version += 1;
    const event: AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17DomainEvent = { type, aggregateId: this.id, version: this._version, occurredOn: new Date(), payload };
    this._events.push(event);
    return event;
  }
}
