/* ==========================================================================
   Generated Domain Contracts & DTO Schemas
   Feature: Autenticación con JWT Middleware en Express.js y Functional Interceptor en Angular 17
   Architecture: Monolith Architecture (MVC / Monolithic)
   Stack: typescript + express + prisma
   Generated by gherkin-ai CLI v3.0.0-beta.1
   ========================================================================== */

import { z } from 'zod';

// --------------------------------------------------------------------------
// 1. Domain Event Interfaces
// --------------------------------------------------------------------------
export interface IDomainEvent {
  eventId: string;
  occurredOn: Date;
  eventType: string;
}



// --------------------------------------------------------------------------
// 2. Command DTO Schemas (Zod Validation)
// --------------------------------------------------------------------------
export const AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17CommandSchema = z.object({
  requestId: z.uuid(),
  timestamp: z.iso.datetime(),
  payload: z.object({

  })
});

export type AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17Command = z.infer<typeof AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17CommandSchema>;

// --------------------------------------------------------------------------
// 3. Domain Repository Port (Outbound Interface)
// --------------------------------------------------------------------------
export interface IAutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17Repository {
  findById(id: string): Promise<unknown | null>;
  save(entity: unknown): Promise<void>;
  delete(id: string): Promise<void>;
}

// --------------------------------------------------------------------------
// 4. Application Event Publisher Port
// --------------------------------------------------------------------------
export interface IEventPublisher {
  publish(event: IDomainEvent): Promise<void>;
}
