/* ==========================================================================
   Generated Test Fixtures & Seed Setup
   Feature: Autenticación con JWT Middleware en Express.js y Functional Interceptor en Angular 17
   Generated by gherkin-ai CLI
   ========================================================================== */

export interface AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17Fixture {
  id: string;

}

export function createAutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17Fixture(): AutenticacionConJwtMiddlewareEnExpressJsYFunctionalInterceptorEnAngular17Fixture {
  return {
    id: 'f47ac10b-58cc-4372-a567-0e02b2c3d479',

  };
}

export const GHERKIN_GIVEN_PRECONDITIONS = [
  "un usuario registrado en el sistema Angular 17"
];
